#!/usr/bin/env bash
# Install and configure Highly Available Proxy

sudo apt-add-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo sed -i "\$ a\listen 261-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 64840-web-01 100.26.247.87:80 check\n\tserver 64840-web-02 3.90.70.167:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
