#!/usr/bin/env bash
# Output "Best School" 10 times using while loop, with "Hi" on 9th loop
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if (( i == 9 ))
    then
        echo "Hi"
    fi
    (( i++ ))
done
