#!/usr/bin/env bash
# Output "Best School" 10 times, with 4th loop being "bad luck" and 8th loop being "good luck"
i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif (( i == 8 ))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done
