#!/usr/bin/env bash
# Output numbers 1 to 20, with different strings for loop 4, 9, and 17

num=1

while (( num < 21 ))
do
    echo $num

    case $num in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    num=$(( num + 1 ))
done
